### ISSUE TITLE
Allow null origin

### ISSUE THREAD

**Issue by boblund** [Winterreisender/webview-nodejs#30]
I've got an html page that can run in a browser or webview. The JS for the browser is in main.mjs and the webview JS is a webpack build main.js.

The html page:

```
<script type="module">
  if ( webview ) {
    await import( './dist/main.js' );
  } else {
    await import( './files/main.mjs ' );
  }
</script>
```

```webview``` is set to true via:

```
w.init(`
    window.webview=true;
`);
```

This works fine when the page is loaded in a browser from a server. In webview though there is the error:

```
Failed to load resource: Origin null is not allowed by Access-Control-Allow-Origin. Status code: 0
```

It would be nice if there was some way to allow origin null.

**Comment by Winterreisender** [comment]
This seems to be related to chromium's `–allow-file-access-from-files` options.  
These steps may help to diagnose the problem. I'll do some of them and you can also try them yourself if you have time:
Check the original C++ github.com/webview/webview to see if it produce the same result. If so, it should be the upstreams C++ project's job to fix this. An if not, it's webview-nodejs's job to fix.

**Comment by Winterreisender** [comment]
The `file://` protocol is banned by our upstream project (https://github.com/webview/webview/issues/859) for safety reasons. And it seems they are planning to use custom URI to fix this (https://github.com/webview/webview/issues/851). As a node.js binding, in my view, we shouldn't heavily modify the source code of our upstream project and this issue should be fixed in upstream instead of here.  
So, the only thing we can do is to wait for the upstream to fix this or offer an alternative way. And after that I'll follow the solution as quickly as I can.
