### ISSUE TITLE
example with keybinding and log

### ISSUE THREAD

**Issue by dirkk0** [Winterreisender/webview-nodejs#4]
Hi,

thanks for the nodejs bindings, much appreciated!

Because it wasn't completely obvious for me I created an example with keybindings (which are platform specific, this is for a Mac) and logging.

Maybe this is helpful for someone.

```
const { Webview } = require("webview-nodejs");

html = `
<body>
  <div id="d1"></div>
  <script>
    let counter = 0
    window.addEventListener("keypress", (event) => {
      if (event.metaKey && event.key === 'q') {
        doCmd("quit")
        event.preventDefault();
      }
    })

    setInterval(function () {
      document.querySelector("#d1").innerText = counter
      doLog("counter is " + counter)
      counter += 1
    }, 1000);
  </script>
</body>
`

let w = new Webview(true);

w.size(600, 600);
w.html(html);

w.bind("doLog", (w, t) => {
  console.log(t);
  w.title(t)
});

w.bind("doCmd", (w, cmd) => {
  console.log("cmd:", cmd);
  if (cmd == "quit") w.terminate();
});

w.show();
```

**Comment by Winterreisender** [comment]
Thanks! Currently I'm preparing for a quite important exam and I'll add this to the examples later.

**Comment by dirkk0** [comment]
no hurries! good luck for your exam!

**Comment by Winterreisender** [comment]
I have added it to examples with a little changes for better compatibility.

1. `keypress` -> `keydown`: Because the `keypress` event is deprecated according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/keypress_event), and doesn't work on Windows
2. `event.metaKey` -> `event.metaKey || event.altKey`: In Windows, the "Windows Search" poped up if you press `⊞+q`. This change would make it works both on Windows and Mac.
